config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    post 'upvote'
    resources :comments do
      get 'reply'
    end
  end

  # resources :comments do
  #   resources :subcomments
  # end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # has_many :replies, class_name: "Comment", foreign_key: "reply_id"
  belongs_to :post
  # belongs_to :reply, class_name: "Comment"
  validates :author, :presence => true
  validates :text, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments

  validates :title , :presence => true
  validates :content , :presence => true
  validates :author , :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end

  def create
    @post = Post.find(params[:post_id])

    @comment = @post.comments.new(comment_params)
    @comment.reply_id = params[:comment][:reply_id].to_i
    if @comment.save
      redirect_to post_path(@comment.post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to post_path(@comment.post)
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@comment.post)
  end

  def reply
    @post = Post.find(params[:post_id])
    @oldComment = Comment.find(params[:comment_id])
    @comment = Comment.new()
    @comment.reply_id = @oldComment.id
  end

private
  def comment_params
    params.require(:comment).permit(:author, :text, :reply_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    filtered_posts = Post.all.sort_by.sort { |a, b| b.score <=> a.score }
    @posts = filtered_posts
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.score = 0;
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def upvote
    @post = Post.find(params[:post_id])
    new_score = @post.score += 1
    @post.update(score: new_score)
    puts("********************************************")
    puts(@post.score)
    redirect_to posts_path
  end

private
  def post_params
    params.require(:post).permit(:title, :author, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= render('layouts/errors', :object => @comment) %>

<%= form_for [@post, @comment] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :text %>
  <%= f.text_field :text %>
  <% if @oldComment != nil %>
    <%= f.hidden_field :reply_id, :value => @oldComment.id %>
  <% end %>
  <p><%= f.submit %></p>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= render 'form' %>

app/views/comments/new.html.erb
<h1>New comment for <%= @post.title %></h1>

<%= render 'form' %>

app/views/comments/reply.html.erb
<h1>Reply to <%= @oldComment.text %></h1>

<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HackerNews</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_comments.html.erb
<%= comment.text %> |
<%= link_to "Reply", post_comment_reply_path(@post, comment) %> |
<%= link_to "Edit", edit_post_comment_path(@post, comment) %> |
<%= link_to "Delete", post_comment_path(@post, comment),
                         :data => {:confirm => "Are you sure?",
                         :method => "delete"} %>

<ul>
  <% @post.comments.each do |subcomment| %>
    <% if subcomment.reply_id == comment.id %>
      <li>
        <%= render partial: "comments", locals: {comment: subcomment} %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/posts/_form.html.erb
<%= render "layouts/errors", :object => @post %>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label "link to article" %>
  <%= f.text_field :content %>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<ol>
  <% @posts.each do |post| %>
    <li>
      <%= button_to '+1', post_upvote_path(post), method: :post  %>
      <%= post.score  %> |
      <%= link_to post.title, post.content %> |
      <%= link_to "comments", post_path(post) %>
    </li>
  <% end %>
</ol>

<%= link_to "New Post", new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<% if @post.comments.any? %>
  <h4>Here are the comments for this post</h4>
  <ul>
    <% @post.comments.each do |comment| %>
      <% if comment.reply_id === 0 %>
        <li>
          <%= render partial: "comments", locals: {comment: comment} %>
        </li>
      <% end %>
    <% end %>
  </ul>

<% else %>
  <p>There are no comments on this post yet.</p>
<% end %>

<p><%= link_to "Add a comment", new_post_comment_path(@post) %></p>
<p><%= link_to "Return to posts", posts_path %></p>

<p><%= link_to "Edit", edit_post_path(@post) %></p>
<p><%= link_to "Delete", post_path(@post),
  :data => {:confirm => "Are you sure?",
            :method => "delete"} %></p>